use_frameworks!

target 'LocalizationKit_Example' do
  pod 'LocalizationKit', :path => '../'
  pod 'MBProgressHUD'
  target 'LocalizationKit_Tests' do
    inherit! :search_paths
    pod 'LocalizationKit', :path => '../'
  end
end
